workflow:
  rules:
    # Don't run simple push pipelines
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      when: never
    # Allow to interrupt pipelines on merge request if a new commit arrives
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      auto_cancel:
        on_new_commit: interruptible
    # Do not interrupt pipelines on main
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      auto_cancel:
        on_new_commit: none

# Suppress certain warnings
variables:
  PIPENV_VERBOSITY: -1

stages:
  - test

formatting:
  stage: test
  tags:
    - test
  script:
    # Use black to verify the correct formatting of all files
    - black --check .
  interruptible: true

pytest:
  stage: test
  tags:
    - test
  script:
    # Use most recent version from Pipfile
    - poetry install --no-root
    # Run all unit tests with coverage
    - poetry run coverage run -m pytest
    # Generate coverage reports
    - coverage html --fail-under=80
    - coverage json --fail-under=80
  interruptible: true
  artifacts:
    # Take whole HTML folder and the json report
    name: "coverage-report-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - htmlcov-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA/*
      - coverage-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA.json
    expire_in: 1 week

